version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./:/var/www/html/wp-content/plugins/mockups
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example